source "https://rubygems.org"

gem "puppet"
gem "librarian-puppet"
gem "puppet-lint"
gem "puppetlabs_spec_helper"
gem "rake"
gem "serverspec"
gem "rspec-puppet-facts"
gem "rspec-puppet"
gem "CFPropertyList"
gem "facter"

gem "test-kitchen"
gem "kitchen-puppet"
gem "kitchen-docker"
gem "docker"
gem "kitchen-inspec"
gem "kitchen-sync"
